#
#####Pre-Initialisation
#Choose a physics list, for a full listing type /A2/physics/ListPhysics or /Pol/physics/ListPhysics
#/Pol/physics/Physics QGSP_BIC_POL
/Pol/physics/Physics QGSP_BIC_POL
#/A2/physics/Physics QGSP_BERT_CHIPS

####Initialise
/run/verbose 1
/run/initialize
#/A2/physics/CutEl 0.01 mm
#/A2/physics/CutsAll 0.01 mm


#17/02/16 CAM commented out all the SetRegion stuff as PolPhysicsList does not contain a region command
/Pol/physics/SetRegion CB
/Pol/physics/RegionCut  0.1 mm
/Pol/physics/SetRegion TAPS
/Pol/physics/RegionCut  0.1 mm
/Pol/physics/SetRegion TAPSV
/Pol/physics/RegionCut 0.01 mm
/Pol/physics/SetRegion PID
/Pol/physics/RegionCut 0.01 mm
/Pol/physics/SetRegion MWPC
/Pol/physics/RegionCut 0.1 mm

##the initial random number seed
/A2/generator/Seed 1111111

#Set the number of particles to be tracked from the input ntuple
/A2/generator/NToBeTracked 4
#give the indexes of the particles to be tracked
#(have a look at the branch names in the input file)
/A2/generator/Track 1
/A2/generator/Track 2
/A2/generator/Track 3
/A2/generator/Track 4
#Open the file and set up the ntuple for reading
#/A2/generator/InputFile /Disk/thehub_disk_5/msikora/GP_PPi0_SAID_hub__1M_99.root
#/A2/generator/InputFile /scratch/chris/AcquMC/GP_PPi0/InitialTest/POL/POL_PPi0_AcquMC_OutputNtuple.root
/A2/generator/InputFile /scratch/chris/AcquMC/GD_PPi0/POL/Neutron/POL_PPi0_AcquMC_OutputNtupleNeutron.root
#####Output
#Open the output file for writing
/A2/event/setOutputFile /scratch/chris/AcquMC/GD_PPi0/POL/Neutron/POL_PPi0_OutputA2SimNeutron.root
